HOOK_REACTION: 'popteamepic-po'
BOT_NAME: 'Unknown'
HOOK_CHANNEL: 'C9G3A9S3B' # https://api.slack.com/methods/channels.list/test
HOOK_KEYWORD: '33-4'
FNC_REACT: 'SlackReactionBot-prd-fnc'
FNC_REPLY: 'SlackReplyBot-prd-fnc'
FNC_ANONY: 'SlackAnonymousChannel-prd-fnc'
HOOK_REACTIONS: 'popteamepic-po,popteamepic-pu,popteamepic-te,popteamepic-pi1,popteamepic-pi2,popteamepic-tsu,popteamepic-ku'
HOOK_CHANNEL_FGO: 'CBZ8VRTG9,CCMT92WTE,C93TCENBH' # fgo,ガチャァァ,bot_test
HOOK_KEYWORD_FGO: 'ガチャァァまわすのぉぉぉ！！,いっぱいいっぱい回すのぉぉぉ！！'
FNC_FGO: 'FgoBot-prd-fnc'
